replicaCount: 1

image:
  repository: ghcr.io/rohekood/pocv
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

# pocv is a pure consumer service (no HTTP endpoint)
service:
  enabled: false

env:
  secretName: tmf-secrets
  rabbitmq:
    secretName: ""
    secretKey: RABBITMQ_URL
  postgres:
    secretName: ""
    secretKey: POCV_DB_URL
  extra: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
