replicaCount: 1

image:
  repository: ghcr.io/rohekood/product-catalog-management
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

# product-catalog-management is a pure consumer service (no HTTP endpoint)
service:
  enabled: false

env:
  secretName: tmf-secrets
  rabbitmq:
    value: ""
    secretKey: RABBITMQ_URL
  postgres:
    value: ""
    secretKey: CATALOG_DB_URL
  extra: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
