---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qualification
  namespace: tmf
spec:
  interval: 5m
  dependsOn:
    - name: postgres
    - name: rabbitmq
    - name: redis
  chart:
    spec:
      chart: ./releases/charts/qualification
      sourceRef:
        kind: GitRepository
        name: tmf-ai-demo
        namespace: flux-system
  values:
    image:
      tag: "latest"
    env:
      secretName: tmf-secrets
      redisAddr: "redis-master.tmf.svc.cluster.local:6379"
