replicaCount: 1

image:
  repository: ghcr.io/rohekood/party-management
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

env:
  secretName: tmf-secrets
  rabbitmq:
    secretName: ""
    secretKey: RABBITMQ_URL
  postgres:
    secretName: ""
    secretKey: PARTY_DB_URL
  extra: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
