apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-ui.fullname" . }}
  labels:
    {{- include "demo-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_URL
              value: {{ .Values.env.apiUrl | quote }}
            - name: API_BASE_URL
              value: {{ .Values.env.apiBaseUrl | quote }}
            {{- if .Values.env.secretName }}
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName | quote }}
                  key: {{ .Values.env.auth0DomainKey | quote }}
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName | quote }}
                  key: {{ .Values.env.auth0ClientIdKey | quote }}
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName | quote }}
                  key: {{ .Values.env.auth0AudienceKey | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
