ALTER TABLE outbox_events
  ALTER COLUMN routing_key TYPE VARCHAR(255),
  ALTER COLUMN status TYPE VARCHAR(50),
  ALTER COLUMN status SET DEFAULT 'PENDING',
  ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE,
  ALTER COLUMN processed_at TYPE TIMESTAMP WITH TIME ZONE;
