ALTER TABLE outbox_events
  ALTER COLUMN routing_key TYPE VARCHAR,
  ALTER COLUMN status TYPE VARCHAR,
  ALTER COLUMN status DROP DEFAULT,
  ALTER COLUMN created_at TYPE TIMESTAMP,
  ALTER COLUMN processed_at TYPE TIMESTAMP;
