---
# Root Kustomization for the tmf namespace.
# Apply with: kubectl apply -k releases/flux/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sources/gitrepository.yaml
  - sources/bitnami-helmrepository.yaml
  - infrastructure/postgres-release.yaml
  - infrastructure/rabbitmq-release.yaml
  - infrastructure/redis-release.yaml
  - apps/customer-management.yaml
  - apps/party-management.yaml
  - apps/product-catalog-management.yaml
  - apps/shopping-cart.yaml
  - apps/qualification.yaml
  - apps/pocv.yaml
  - apps/bff.yaml
  - apps/demo-ui.yaml
