replicaCount: 1

image:
  repository: ghcr.io/rohekood/demo-ui
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

env:
  secretName: ""
  auth0DomainKey: AUTH0_DOMAIN
  auth0ClientIdKey: AUTH0_CLIENT_ID
  auth0AudienceKey: AUTH0_AUDIENCE
  apiUrl: /api
  apiBaseUrl: ""
  bffHost: "bff"

# Runtime variables are injected from Kubernetes into the container and rendered
# into /config.js at startup.
# AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_AUDIENCE, API_URL, API_BASE_URL

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
