apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-catalog-management.fullname" . }}
  labels:
    {{- include "product-catalog-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "product-catalog-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "product-catalog-management.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_URL
              {{- if .Values.env.postgres.value }}
              value: {{ .Values.env.postgres.value | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.postgres.secretKey }}
              {{- end }}
            - name: RABBITMQ_URL
              {{- if .Values.env.rabbitmq.value }}
              value: {{ .Values.env.rabbitmq.value | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: {{ .Values.env.rabbitmq.secretKey }}
              {{- end }}
            {{- with .Values.env.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
