replicaCount: 1

image:
  repository: ghcr.io/rohekood/shopping-cart
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

# shopping-cart is a pure consumer service (no HTTP endpoint)
service:
  enabled: false

env:
  secretName: tmf-secrets
  extra: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
