apiVersion: v2
name: tmf-platform
description: Umbrella chart for deploying all TMF AI Demo application services
type: application
version: 0.3.1
appVersion: "latest"

dependencies:
  - name: bff
    version: ">=0.0.0-0"
    repository: file://../bff
    alias: bff
    condition: bff.enabled
  - name: customer-management
    version: ">=0.0.0-0"
    repository: file://../customer-management
    alias: customer-management
    condition: customer-management.enabled
  - name: demo-ui
    version: ">=0.0.0-0"
    repository: file://../demo-ui
    alias: demo-ui
    condition: demo-ui.enabled
  - name: party-management
    version: ">=0.0.0-0"
    repository: file://../party-management
    alias: party-management
    condition: party-management.enabled
  - name: pocv
    version: ">=0.0.0-0"
    repository: file://../pocv
    alias: pocv
    condition: pocv.enabled
  - name: product-catalog-management
    version: ">=0.0.0-0"
    repository: file://../product-catalog-management
    alias: product-catalog-management
    condition: product-catalog-management.enabled
  - name: qualification
    version: ">=0.0.0-0"
    repository: file://../qualification
    alias: qualification
    condition: qualification.enabled
  - name: shopping-cart
    version: ">=0.0.0-0"
    repository: file://../shopping-cart
    alias: shopping-cart
    condition: shopping-cart.enabled
