# Enable/disable subcharts
bff:
  enabled: true
customerManagement:
  enabled: true
demoUi:
  enabled: true
partyManagement:
  enabled: true
pocv:
  enabled: true
productCatalogManagement:
  enabled: true
qualification:
  enabled: true
shoppingCart:
  enabled: true

# Pass-through values to each child chart below these keys.
# Example:
# bff:
#   enabled: true
#   image:
#     tag: "main-123"
#   env:
#     secretName: tmf-secrets
#     rabbitmq:
#       secretName: ""
#       secretKey: RABBITMQ_URL
#
# partyManagement:
#   enabled: true
#   env:
#     postgres:
#       secretName: ""
#       secretKey: PARTY_DB_URL
#     rabbitmq:
#       secretName: ""
#       secretKey: RABBITMQ_URL
#
# qualification:
#   enabled: true
#   env:
#     redis:
#       addr: "valkey-master.tmf.svc.cluster.local:6379"
#       secretName: ""
#       addrSecretKey: ""
#       passwordSecretKey: REDIS_PASSWORD
