---
name: POCV CI/CD

'on':
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
    paths:
      - 'services/pocv/**'
      - 'pkg/**'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/_service-ci-template.yml
    permissions:
      contents: write
      packages: write
    with:
      service_name: pocv
      service_path: services/pocv
      docker_context_path: .
      image_name: pocv
      release_title: POCV
    secrets: inherit
