---
name: Qualification CI/CD

'on':
  push:
    branches:
      - main
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
    paths:
      - 'services/qualification/**'
      - 'pkg/**'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/_service-ci-template.yml
    permissions:
      contents: write
      packages: write
    with:
      service_name: qualification
      service_path: services/qualification
      docker_context_path: .
      image_name: qualification
      release_title: Qualification
    secrets: inherit
