---
name: Shopping Cart CI/CD

'on':
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
      - 'feat/**'
      - 'fix/**'
    paths:
      - 'services/shopping-cart/**'
      - 'pkg/**'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/_service-ci-template.yml
    permissions:
      contents: write
      packages: write
    with:
      service_name: shopping-cart
      service_path: services/shopping-cart
      docker_context_path: .
      image_name: shopping-cart
      release_title: Shopping Cart
    secrets: inherit
